name: Sharp Swords & Sinister Spells
url: http://oldskulling.blogspot.com/
credit: Diogo Nogueira / Old Skull Publishing

groups:
  - name: grpAdventure
    uiName: Adventures
    icon: cmd-sword-cross
  - name: grpBetweenAdventure
    uiName: Between Adventures
    icon: cmd-timer-sand
  - name: grpChar
    uiName: Characters
    icon: cmd-account
  - name: grpEncounter
    uiName: Encounters
    icon: cmd-run
  - name: grpNPC
    uiName: NPCs
    icon: cmd-account-multiple

attribution: |
  <a href="http://www.drivethrurpg.com/product/198163/Sharp-Swords--Sinister-Spells">Sharp Swords & Sinister Spells on DriveThruRPG</a>
  <br/><br/><a href="http://www.drivethrurpg.com/product/219747/Sharp-Swords--Sinister-Spells--Addendum">Sharp Swords & Sinister Spells Addendum on DriveThruRPG</a>

  <br/><br/><a href="http://www.drivethrurpg.com/product/204344/Lost-Folios-of-the-Book-of-Creation-1--Adventure-Title-Generator">Lost Folios of the Book of Creation #1  on DriveThruRPG</a>


  <h4><cite>Sharp Swords & Sinister Spells</cite> Open Content in Adventuresmith</h4>
  <p>The text from <cite>Sharp Swords & Sinister Spells</cite> included in Adventuresmith is located
  <a href="https://github.com/stevesea/Adventuresmith/tree/master/adventuresmith-core/src/main/resources/org/stevesea/adventuresmith/core/ss_and_ss">here</a>
  in the Adventuresmith github repository. </p>

  <blockquote>
  <h4>What is Sharp Swords & Sinister Spells?</h4>
  <p>Sharp Swords & Sinister Spells is a rules-light, sword & sorcery, old school role playing game
  inspired by the original fantasy RPG and the Old School Renaissance movement as well as the
  stories by such authors as Robert E. Howard, Clark Ashton Smith, H.P. Lovecraft, Fritz Leiber
  and Michael Moorcock. With this book, you and your friends will be able to play exciting adventures
  with bold barbarians, witty thieves and cunning sorcerers without worrying about complex rules and
  tiresome preparations.</p>

  <p>ATTENTION! Sharp Swords & Sinister Spells is not a Simulacrum of an older edition of the world’s
  most famous fantasy RPG! Although inspired by the original game and the OSR movement, the game
  was designed to be have its own unique system, more suitable to the Sword & Sorcery genre the
  author has in mind. The following author's work inspired the mechanics of this game: Gary Gygax,
  Dave Arneson, David Black, Christian Mehrstam, John Cocking, Peter S. Williams, Joseph Goodman,
  Harley Stroh, Jason Morningstar, Ian Livingstone, Steve Jackson, Simon Washbourne, Kevin Crawford,
  Sandy Petersen, Mike Manson, Jay Little, James M. Spahn, Ben Milton.</p>
  </blockquote>
  </p>
  <blockquote>
  Open Game License (OGL 1.0a)
  <h5>INTRODUCTION</h5>
  Sharp Swords & Sinister Spells is based on the System Reference
  Document v3.5 (“SRD”), which is Open Game Content. The text
  of the Open Game License itself is not Open Game Content.
  Instructions on using the License are provided within the License
  itself.
  <br/>Designation of Open Game Content: The entire text in this book
  (except the Open Game License, as noted above, and the Product
  Identity License, below) is Open Game Content, released under
  the Open Game License, Version 1.0a (reproduced below) as
  described in Section 1(d) of the License. Artwork incorporated
  in this document is not Open Game Content, and remains the
  property of the copyright holder.</p>
  <br/>Designation of Product Identity: Product identity is not Open
  Game Content. The following is designated as product identity
  pursuant to OGL v1.0a(1)(e) and (7): (A) product and product
  line names, including Sharp Swords & Sinister Spells; (B) all
  artwork, logos, symbols, graphic designs, depictions, likenesses,
  formats, poses, concepts, themes and graphic, photographic and
  other visual representations; © logos and trademarks, including
  any trademark or registered trademark clearly identified as
  product identity by the owner of the product identity, and which
  specifically excludes the open game content.
  <br/>More information on the Open Game License can be found at:
  http://www.wizards.com/d20
  <h5>OPEN GAME LICENSE VERSION 1.0A</h5>
  The following text is the property of Wizards of the Coast, Inc.
  and is Copyright 2000 Wizards of the Coast, Inc (“Wizards”). All
  Rights Reserved.
  <br/>1. Definitions: (a)“Contributors” means the copyright and/or
  trademark owners who have contributed Open Game Content;
  (b)“Derivative Material” means copyrighted material including
  derivative works and translations (including into other computer
  languages), potation, modification, correction, addition,
  extension, upgrade, improvement, compilation, abridgment or
  other form in which an existing work may be recast, transformed
  or adapted; © “Distribute” means to reproduce, license, rent,
  lease, sell, broadcast, publicly display, transmit or otherwise
  distribute; (d)“Open Game Content” means the game mechanic
  and includes the methods, procedures, processes and routines
  to the extent such content does not embody the Product Identity
  and is an enhancement over the prior art and any additional
  content clearly identified as Open Game Content by the
  Contributor, and means any work covered by this License,
  including translations and derivative works under copyright law,
  but specifically excludes Product Identity. (e) “Product Identity”
  means product and product line names, logos and identifying
  marks including trade dress; artifacts; creatures characters;
  stories, storylines, plots, thematic elements, dialogue, incidents,
  language, artwork, symbols, designs, depictions, likenesses,
  formats, poses, concepts, themes and graphic, photographic and
  other visual or audio representations; names and descriptions of
  characters, spells, enchantments, personalities, teams, personas,
  likenesses and special abilities; places, locations, environments,
  creatures, equipment, magical or supernatural abilities or effects,
  logos, symbols, or graphic designs; and any other trademark or
  registered trademark clearly identified as Product identity by the
  owner of the Product Identity, and which specifically excludes
  the Open Game Content; (f) “Trademark” means the logos,
  names, mark, sign, motto, designs that are used by a Contributor
  to identify itself or its products or the associated products
  contributed to the Open Game License by the Contributor
  (g) “Use”, “Used” or “Using” means to use, Distribute, copy,
  edit, format, modify, translate and otherwise create Derivative
  Material of Open Game Content. (h) “You” or “Your” means the
  licensee in terms of this agreement.
  <br/>2. The License: This License applies to any Open Game Content
  that contains a notice indicating that the Open Game Content
  may only be Used under and in terms of this License. You must
  affix such a notice to any Open Game Content that you Use. No
  terms may be added to or subtracted from this License except
  as described by the License itself. No other terms or conditions
  may be applied to any Open Game Content distributed using
  this License.
  <br/>3. Offer and Acceptance: By Using the Open Game Content You
  indicate Your acceptance of the terms of this License.
  <br/>4. Grant and Consideration: In consideration for agreeing to use
  this License, the Contributors grant You a perpetual, worldwide,
  royalty-free, nonexclusive license with the exact terms of this
  License to Use, the Open Game Content.
  <br/>5. Representation of Authority to Contribute: If You are
  contributing original material as Open Game Content, You
  represent that Your Contributions are Your original creation and/
  or You have sufficient rights to grant the rights conveyed by this
  License.
  <br/>6. Notice of License Copyright: You must update the
  COPYRIGHT NOTICE portion of this License to include the
  exact text of the COPYRIGHT NOTICE of any Open Game
  Content You are copying, modifying or distributing, and You
  must add the title, the copyright date, and the copyright holder’s
  name to the COPYRIGHT NOTICE of any original Open Game
  Content you Distribute.
  <br/>7. Use of Product Identity: You agree not to Use any Product
  Identity, including as an indication as to compatibility, except as
  expressly licensed in another, independent Agreement with the
  owner of each element of that Product Identity. You agree not
  to indicate compatibility or co-adaptability with any Trademark
  or Registered Trademark in conjunction with a work containing
  Open Game Content except as expressly licensed in another,
  independent Agreement with the owner of such Trademark or
  Registered Trademark. The use of any Product Identity in Open
  Game Content does not constitute a challenge to the ownership
  of that Product Identity. The owner of any Product Identity used
  in Open Game Content shall retain all rights, title and interest in
  and to that Product Identity.
  <br/>8. Identification: If you distribute Open Game Content You
  must clearly indicate which portions of the work that you are
  distributing are Open Game Content.
  <br/>9. Updating the License: Wizards or its designated Agents may
  publish updated versions of this License. You may use any
  authorized version of this License to copy, modify and distribute
  any Open Game Content originally distributed under any
  version of this License.
  <br/>10. Copy of this License: You MUST include a copy of this License
  with every copy of the Open Game Content You Distribute.
  <br/>11. Use of Contributor Credits: You may not market or advertise
  the Open Game Content using the name of any Contributor
  unless You have written permission from the Contributor to do
  so.
  <br/>12. Inability to Comply: If it is impossible for You to comply
  with any of the terms of this License with respect to some or
  all of the Open Game Content due to statute, judicial order, or
  governmental regulation then You may not Use any Open Game
  Material so affected.
  <br/>13. Termination: This License will terminate automatically if You
  fail to comply with all terms herein and fail to cure such breach
  within 30 days of becoming aware of the breach. All sublicenses
  shall survive the termination of this License.
  <br/>14. Reformation: If any provision of this License is held to be
  unenforceable, such provision shall be reformed only to the
  extent necessary to make it enforceable.
  <br/>15. COPYRIGHT NOTICE
  Open Game License v 1.0 Copyright ©2000, Wizards of the Coast, Inc.
  <br/>System Reference Document Copyright ©2000-2003, Wizards
  of the Coast, Inc.; Authors Jonathan Tweet, Monte Cook, Skip
  Williams, Rich Baker, Andy Collins, David Noonan, Rich
  Redman, Bruce R. Cordell, John D. Rateliff, Thomas Reid, James
  Wyatt, based on original material by E. Gary Gygax and Dave
  Arneson.
  <br/>The original roleplaying game “The Black Hack” text, tables, all
  artwork, logos and layout are Copyright 2016, David Black.
  “Additional Things” text, tables, artwork and layout are Copyright 2016, David Black.
  <br/>“Sharp Swords & Sinister Spells” Copyright ©2016 Diogo  Nogueira.
  </blockquote>