name: Hack & Slash
id: hack_and_slash
priority: 100
credit: Courtney C. Campbell
url: "http://hackslashmaster.blogspot.com/"
attribution: |
  <h5>Tricks, Empty Rooms, & Basic Trap Design</h5>
  http://hackslashmaster.blogspot.com/2011/02/on-tricks-empty-rooms-and-basic-trap.html
