name: Hack & Slash
credit: Courtney C. Campbell
url: "http://hackslashmaster.blogspot.com/"
attribution: |
  <h5>Tricks, Empty Rooms, & Basic Trap Design</h5>
  All text is © Courtney C. Campbell (2011).
  <br/>
  <br/><a href="http://hackslashmaster.blogspot.com/2011/02/on-tricks-empty-rooms-and-basic-trap.html">Tricks, Empty Rooms, & Basic Trap Design</a>



